package storage

type Phrase struct {
	Prompt   string
	Expected string
}

var PhraseSets = map[string][]Phrase{

	"default": {
		{Prompt: "hello", Expected: "привет"},
		{Prompt: "water", Expected: "вода"},
		{Prompt: "house", Expected: "дом"},
		{Prompt: "friend", Expected: "друг"},
		{Prompt: "school", Expected: "школа"},
		{Prompt: "city", Expected: "город"},
		{Prompt: "country", Expected: "страна"},
		{Prompt: "family", Expected: "семья"},
		{Prompt: "mother", Expected: "мама"},
		{Prompt: "father", Expected: "папа"},
		{Prompt: "brother", Expected: "брат"},
		{Prompt: "sister", Expected: "сестра"},
		{Prompt: "work", Expected: "работа"},
		{Prompt: "money", Expected: "деньги"},
		{Prompt: "time", Expected: "время"},
		{Prompt: "day", Expected: "день"},
		{Prompt: "night", Expected: "ночь"},
		{Prompt: "year", Expected: "год"},
		{Prompt: "week", Expected: "неделя"},
		{Prompt: "month", Expected: "месяц"},
		{Prompt: "sun", Expected: "солнце"},
		{Prompt: "moon", Expected: "луна"},
		{Prompt: "star", Expected: "звезда"},
		{Prompt: "book", Expected: "книга"},
		{Prompt: "table", Expected: "стол"},
		{Prompt: "chair", Expected: "стул"},
		{Prompt: "door", Expected: "дверь"},
		{Prompt: "window", Expected: "окно"},
		{Prompt: "road", Expected: "дорога"},
		{Prompt: "river", Expected: "река"},
	},

	"animals": {
		{Prompt: "cat", Expected: "кот"},
		{Prompt: "dog", Expected: "собака"},
		{Prompt: "camel", Expected: "верблюд"},
		{Prompt: "horse", Expected: "лошадь"},
		{Prompt: "bear", Expected: "медведь"},
		{Prompt: "lion", Expected: "лев"},
		{Prompt: "tiger", Expected: "тигр"},
		{Prompt: "wolf", Expected: "волк"},
		{Prompt: "fox", Expected: "лиса"},
		{Prompt: "rabbit", Expected: "кролик"},
		{Prompt: "mouse", Expected: "мышь"},
		{Prompt: "cow", Expected: "корова"},
		{Prompt: "pig", Expected: "свинья"},
		{Prompt: "goat", Expected: "коза"},
		{Prompt: "sheep", Expected: "овца"},
		{Prompt: "chicken", Expected: "курица"},
		{Prompt: "duck", Expected: "утка"},
		{Prompt: "eagle", Expected: "орёл"},
		{Prompt: "snake", Expected: "змея"},
		{Prompt: "fish", Expected: "рыба"},
		{Prompt: "whale", Expected: "кит"},
		{Prompt: "shark", Expected: "акула"},
		{Prompt: "monkey", Expected: "обезьяна"},
		{Prompt: "zebra", Expected: "зебра"},
		{Prompt: "elephant", Expected: "слон"},
		{Prompt: "kangaroo", Expected: "кенгуру"},
		{Prompt: "deer", Expected: "олень"},
		{Prompt: "frog", Expected: "лягушка"},
		{Prompt: "parrot", Expected: "попугай"},
		{Prompt: "owl", Expected: "сова"},
	},

	"travel": {
		{Prompt: "ticket", Expected: "билет"},
		{Prompt: "airport", Expected: "аэропорт"},
		{Prompt: "train", Expected: "поезд"},
		{Prompt: "hotel", Expected: "отель"},
		{Prompt: "passport", Expected: "паспорт"},
		{Prompt: "visa", Expected: "виза"},
		{Prompt: "luggage", Expected: "багаж"},
		{Prompt: "map", Expected: "карта"},
		{Prompt: "guide", Expected: "гид"},
		{Prompt: "journey", Expected: "путешествие"},
		{Prompt: "station", Expected: "станция"},
		{Prompt: "platform", Expected: "платформа"},
		{Prompt: "bus", Expected: "автобус"},
		{Prompt: "ship", Expected: "корабль"},
		{Prompt: "boat", Expected: "лодка"},
		{Prompt: "border", Expected: "граница"},
		{Prompt: "customs", Expected: "таможня"},
		{Prompt: "flight", Expected: "рейс"},
		{Prompt: "departure", Expected: "вылет"},
		{Prompt: "arrival", Expected: "прибытие"},
		{Prompt: "tourist", Expected: "турист"},
		{Prompt: "guidebook", Expected: "путеводитель"},
		{Prompt: "reservation", Expected: "бронь"},
		{Prompt: "car", Expected: "машина"},
		{Prompt: "taxi", Expected: "такси"},
		{Prompt: "road", Expected: "дорога"},
		{Prompt: "bridge", Expected: "мост"},
		{Prompt: "mountain", Expected: "гора"},
		{Prompt: "beach", Expected: "пляж"},
		{Prompt: "island", Expected: "остров"},
	},

	"food": {
		{Prompt: "bread", Expected: "хлеб"},
		{Prompt: "milk", Expected: "молоко"},
		{Prompt: "cheese", Expected: "сыр"},
		{Prompt: "apple", Expected: "яблоко"},
		{Prompt: "salt", Expected: "соль"},
		{Prompt: "sugar", Expected: "сахар"},
		{Prompt: "butter", Expected: "масло"},
		{Prompt: "meat", Expected: "мясо"},
		{Prompt: "fish", Expected: "рыба"},
		{Prompt: "chicken", Expected: "курица"},
		{Prompt: "rice", Expected: "рис"},
		{Prompt: "potato", Expected: "картофель"},
		{Prompt: "tomato", Expected: "помидор"},
		{Prompt: "cucumber", Expected: "огурец"},
		{Prompt: "carrot", Expected: "морковь"},
		{Prompt: "onion", Expected: "лук"},
		{Prompt: "garlic", Expected: "чеснок"},
		{Prompt: "egg", Expected: "яйцо"},
		{Prompt: "coffee", Expected: "кофе"},
		{Prompt: "tea", Expected: "чай"},
		{Prompt: "juice", Expected: "сок"},
		{Prompt: "cake", Expected: "торт"},
		{Prompt: "soup", Expected: "суп"},
		{Prompt: "salad", Expected: "салат"},
		{Prompt: "pizza", Expected: "пицца"},
		{Prompt: "burger", Expected: "бургер"},
		{Prompt: "sausage", Expected: "колбаса"},
		{Prompt: "pancake", Expected: "блин"},
		{Prompt: "honey", Expected: "мёд"},
		{Prompt: "pepper", Expected: "перец"},
	},
}
