package storage

type Phrase struct {
	Prompt   string
	Expected string
}

// PhraseSets[topic][difficulty]
var PhraseSets = map[string]map[string][]Phrase{
	"default": {
		"beginner": {
			{Prompt: "cat", Expected: "кот"},
			{Prompt: "dog", Expected: "собака"},
			{Prompt: "sun", Expected: "солнце"},
			{Prompt: "moon", Expected: "луна"},
			{Prompt: "book", Expected: "книга"},
			{Prompt: "water", Expected: "вода"},
			{Prompt: "fire", Expected: "огонь"},
			{Prompt: "tree", Expected: "дерево"},
			{Prompt: "house", Expected: "дом"},
			{Prompt: "car", Expected: "машина"},
		},
		"intermediate": {
			{Prompt: "hello", Expected: "привет"},
			{Prompt: "friend", Expected: "друг"},
			{Prompt: "family", Expected: "семья"},
			{Prompt: "school", Expected: "школа"},
			{Prompt: "city", Expected: "город"},
			{Prompt: "country", Expected: "страна"},
			{Prompt: "mother", Expected: "мама"},
			{Prompt: "father", Expected: "папа"},
			{Prompt: "brother", Expected: "брат"},
			{Prompt: "sister", Expected: "сестра"},
			{Prompt: "work", Expected: "работа"},
			{Prompt: "money", Expected: "деньги"},
			{Prompt: "time", Expected: "время"},
			{Prompt: "day", Expected: "день"},
			{Prompt: "night", Expected: "ночь"},
		},
		"advanced": {
			{Prompt: "beautiful", Expected: "красивый"},
			{Prompt: "wonderful", Expected: "замечательный"},
			{Prompt: "important", Expected: "важный"},
			{Prompt: "different", Expected: "разный"},
			{Prompt: "together", Expected: "вместе"},
			{Prompt: "something", Expected: "что-то"},
			{Prompt: "everything", Expected: "всё"},
			{Prompt: "sometimes", Expected: "иногда"},
			{Prompt: "everywhere", Expected: "повсюду"},
			{Prompt: "understand", Expected: "понимать"},
			{Prompt: "remember", Expected: "помнить"},
			{Prompt: "believe", Expected: "верить"},
			{Prompt: "become", Expected: "становиться"},
			{Prompt: "because", Expected: "потому что"},
			{Prompt: "although", Expected: "хотя"},
		},
	},
	"animals": {
		"beginner": {
			{Prompt: "cat", Expected: "кот"},
			{Prompt: "dog", Expected: "собака"},
			{Prompt: "bird", Expected: "птица"},
			{Prompt: "fish", Expected: "рыба"},
			{Prompt: "frog", Expected: "лягушка"},
		},
		"intermediate": {
			{Prompt: "horse", Expected: "лошадь"},
			{Prompt: "bear", Expected: "медведь"},
			{Prompt: "lion", Expected: "лев"},
			{Prompt: "wolf", Expected: "волк"},
			{Prompt: "fox", Expected: "лиса"},
			{Prompt: "rabbit", Expected: "кролик"},
			{Prompt: "mouse", Expected: "мышь"},
			{Prompt: "cow", Expected: "корова"},
			{Prompt: "pig", Expected: "свинья"},
			{Prompt: "sheep", Expected: "овца"},
			{Prompt: "chicken", Expected: "курица"},
			{Prompt: "duck", Expected: "утка"},
		},
		"advanced": {
			{Prompt: "camel", Expected: "верблюд"},
			{Prompt: "tiger", Expected: "тигр"},
			{Prompt: "elephant", Expected: "слон"},
			{Prompt: "kangaroo", Expected: "кенгуру"},
			{Prompt: "zebra", Expected: "зебра"},
			{Prompt: "monkey", Expected: "обезьяна"},
			{Prompt: "parrot", Expected: "попугай"},
			{Prompt: "dolphin", Expected: "дельфин"},
			{Prompt: "whale", Expected: "кит"},
			{Prompt: "shark", Expected: "акула"},
			{Prompt: "giraffe", Expected: "жираф"},
			{Prompt: "penguin", Expected: "пингвин"},
		},
	},
	"travel": {
		"beginner": {
			{Prompt: "bus", Expected: "автобус"},
			{Prompt: "train", Expected: "поезд"},
			{Prompt: "ship", Expected: "корабль"},
			{Prompt: "car", Expected: "машина"},
			{Prompt: "taxi", Expected: "такси"},
		},
		"intermediate": {
			{Prompt: "ticket", Expected: "билет"},
			{Prompt: "airport", Expected: "аэропорт"},
			{Prompt: "hotel", Expected: "отель"},
			{Prompt: "passport", Expected: "паспорт"},
			{Prompt: "visa", Expected: "виза"},
			{Prompt: "luggage", Expected: "багаж"},
			{Prompt: "map", Expected: "карта"},
			{Prompt: "guide", Expected: "гид"},
			{Prompt: "station", Expected: "станция"},
			{Prompt: "flight", Expected: "рейс"},
		},
		"advanced": {
			{Prompt: "journey", Expected: "путешествие"},
			{Prompt: "platform", Expected: "платформа"},
			{Prompt: "border", Expected: "граница"},
			{Prompt: "customs", Expected: "таможня"},
			{Prompt: "departure", Expected: "вылет"},
			{Prompt: "arrival", Expected: "прибытие"},
			{Prompt: "reservation", Expected: "бронь"},
			{Prompt: "guidebook", Expected: "путеводитель"},
			{Prompt: "accommodation", Expected: "проживание"},
			{Prompt: "destination", Expected: "направление"},
		},
	},
	"food": {
		"beginner": {
			{Prompt: "bread", Expected: "хлеб"},
			{Prompt: "milk", Expected: "молоко"},
			{Prompt: "apple", Expected: "яблоко"},
			{Prompt: "meat", Expected: "мясо"},
			{Prompt: "egg", Expected: "яйцо"},
		},
		"intermediate": {
			{Prompt: "cheese", Expected: "сыр"},
			{Prompt: "butter", Expected: "масло"},
			{Prompt: "coffee", Expected: "кофе"},
			{Prompt: "tea", Expected: "чай"},
			{Prompt: "sugar", Expected: "сахар"},
			{Prompt: "salt", Expected: "соль"},
			{Prompt: "rice", Expected: "рис"},
			{Prompt: "potato", Expected: "картофель"},
			{Prompt: "tomato", Expected: "помидор"},
			{Prompt: "onion", Expected: "лук"},
		},
		"advanced": {
			{Prompt: "cucumber", Expected: "огурец"},
			{Prompt: "carrot", Expected: "морковь"},
			{Prompt: "garlic", Expected: "чеснок"},
			{Prompt: "pancake", Expected: "блин"},
			{Prompt: "sausage", Expected: "колбаса"},
			{Prompt: "restaurant", Expected: "ресторан"},
			{Prompt: "vegetables", Expected: "овощи"},
			{Prompt: "ingredients", Expected: "ингредиенты"},
			{Prompt: "appetite", Expected: "аппетит"},
			{Prompt: "delicious", Expected: "вкусный"},
		},
	},
	"movies": {
		"beginner": {
			{Prompt: "film", Expected: "фильм"},
			{Prompt: "movie", Expected: "кино"},
			{Prompt: "actor", Expected: "актёр"},
			{Prompt: "star", Expected: "звезда"},
			{Prompt: "hero", Expected: "герой"},
		},
		"intermediate": {
			{Prompt: "cinema", Expected: "кинотеатр"},
			{Prompt: "director", Expected: "режиссёр"},
			{Prompt: "camera", Expected: "камера"},
			{Prompt: "scene", Expected: "сцена"},
			{Prompt: "sound", Expected: "звук"},
			{Prompt: "music", Expected: "музыка"},
			{Prompt: "story", Expected: "история"},
			{Prompt: "ending", Expected: "конец"},
		},
		"advanced": {
			{Prompt: "performance", Expected: "выступление"},
			{Prompt: "production", Expected: "производство"},
			{Prompt: "screenplay", Expected: "сценарий"},
			{Prompt: "characters", Expected: "персонажи"},
			{Prompt: "atmosphere", Expected: "атмосфера"},
			{Prompt: "emotions", Expected: "эмоции"},
		},
	},
	"sports": {
		"beginner": {
			{Prompt: "ball", Expected: "мяч"},
			{Prompt: "game", Expected: "игра"},
			{Prompt: "goal", Expected: "гол"},
			{Prompt: "team", Expected: "команда"},
			{Prompt: "play", Expected: "играть"},
		},
		"intermediate": {
			{Prompt: "football", Expected: "футбол"},
			{Prompt: "tennis", Expected: "теннис"},
			{Prompt: "hockey", Expected: "хоккей"},
			{Prompt: "player", Expected: "игрок"},
			{Prompt: "coach", Expected: "тренер"},
			{Prompt: "stadium", Expected: "стадион"},
			{Prompt: "match", Expected: "матч"},
			{Prompt: "score", Expected: "счёт"},
		},
		"advanced": {
			{Prompt: "championship", Expected: "чемпионат"},
			{Prompt: "tournament", Expected: "турнир"},
			{Prompt: "victory", Expected: "победа"},
			{Prompt: "competition", Expected: "соревнование"},
			{Prompt: "training", Expected: "тренировка"},
			{Prompt: "performance", Expected: "выступление"},
		},
	},
}

func GetPhrases(topic, difficulty string) []Phrase {
	if topicData, ok := PhraseSets[topic]; ok {
		if phrases, ok := topicData[difficulty]; ok {
			return phrases
		}
	}
	return nil
}
